java -cp Leopard.jar ac.LeopardMain  com.fr3ts0n.ecu.gui.androbd.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.machiav3lli.backup.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.dozingcatsoftware.bouncy.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.cweb.messenger.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  godau.fynn.usagedirect.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  mobi.omegacentauri.SendReduced.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.i2p.android.router.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.sudoq.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  fr.gouv.android.stopcovid.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  is.xyz.omw.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  it.niedermann.owncloud.notes.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  ch.hgdev.toposuite.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  top.donmor.tiddloid.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.tadris.fitness.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.pfiers.osmfocus.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  su.sadrobot.yashlang.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  ru.yanus171.feedexfork.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  dev.corruptedark.openchaoschess.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.corona.tracing.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.osmand.plus.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.farmerbb.taskbar.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.drhoffmannsoftware.calcvac.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.nhiroki.bluelineconsole.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.securefilemanager.app.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  app.fedilab.tubelab.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  org.snikket.android.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.eidottermihi.raspicheck.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.github.axet.audiorecorder.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.reimardoeffinger.quickdic.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.cg.lrceditor.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.sapuseven.untis.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.ichi2.anki.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.shatteredpixel.shatteredpixeldungeon.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  posidon.launcher.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.subhamtyagi.ocr.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.smartpack.smartflasher.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  im.status.ethereum.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  nodomain.freeyourgadget.gadgetbridge.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.mikifus.padland.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.silinote.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.nextcloud.client.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  la.daube.photochiotte.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.installalogs.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.iatfei.streakalarm.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.gimranov.zandy.app.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  me.blog.korn123.easydiary.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.simplemobiletools.gallery.pro.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.poupa.attestationdeplacement.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.ubergeek42.WeechatAndroid.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.sourceforge.opencamera.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  it.niedermann.nextcloud.deck.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.tunerly.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.storchp.opentracks.osmplugin.offline.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  me.tripsit.tripmobile.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  se.lublin.mumla.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.tnibler.cryptocam.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  espero.jiofibatterynotifier.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  security.pEp.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.storchp.opentracks.osmplugin.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.github.cvzi.darkmodewallpaper.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.mendhak.gpslogger.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  app.fedilab.lite.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.fff.ccgt.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.rwth_aachen.phyphox.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.limbo.emu.main.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.smartpack.packagemanager.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.limelight.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.ghostsq.commander.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.alienpants.leafpicrevived.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.wireguard.android.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  t20kdc.offlinepuzzlesolver.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.dar.nclientv2.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  theredspy15.ltecleanerfoss.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.smartpack.scriptmanager.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.monocles.chat.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.osfans.trime.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  eu.veldsoft.ithaka.board.game.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  namlit.siteswapgenerator.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.chronosx88.yggdrasil.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.syss.MifareClassicTool.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  app.fedilab.fedilabtube.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  fr.gouv.etalab.mastodon.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  eu.siacs.conversations.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.appmindlab.nano.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.oF2pks.classyshark3xodus.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  app.fedilab.mobilizon.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.nextcloud.android.beta.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.owncloud.android.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.machiav3lli.derdiedas.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.datastopwatch.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.igisw.openmoneybox.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  player.efis.cfd.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.gh4a.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.saveastxt.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.asdoi.gymwen.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.pixart.messenger.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  godau.fynn.usagedirect.system.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.github.axet.bookreader.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.nulide.findmydevice.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.jovial.jrpn.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  dev.msfjarvis.aps.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.kollnig.missioncontrol.fdroid.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.perflyst.twire.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.github.gschwind.fiddle_assistant.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  at.jclehner.rxdroid.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.smartpack.kernelprofiler.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  xyz.myachin.downloader.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.randomfilemaker.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.kylecorry.trail_sense.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.brentpanther.bitcoinwidget.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.luhmer.owncloudnewsreader.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.muntashirakon.AppManager.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.blau.android.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  menion.android.whereyougo.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.haringeymobile.ukweather.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.ominous.quickweather.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.dosse.bwentrain.androidPlayer.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  kiwi.root.an2linuxclient.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.zoffcc.applications.trifa.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  xyz.myachin.saveto.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.justdave.nwsweatheralertswidget.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.spisoft.quicknote.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  dnsfilter.android.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  eu.sum7.conversations.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  sushi.hardcore.droidfs.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  apps.amine.bou.readerforselfoss.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.rochefort.childmonitor.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.github.axet.torrentclient.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.sourceforge.x11basic.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.freerdp.afreerdp.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.dosse.dozeoff.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  io.github.folderlogs.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  vocabletrainer.heinecke.aron.vocabletrainer.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  ltd.evilcorp.atox.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.calcitem.sanmill.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.smartpack.kernelmanager.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.bible.android.activity.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  lu.fisch.canze.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  net.ktnx.mobileledger.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.apk.editor.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.dosse.airpods.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  com.swordfish.lemuroid.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  im.quicksy.client.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.dennisguse.opentracks.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  site.leos.apps.lespas.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  player.efis.mfd.apk >>Leopard_app.txt   2>&1
java -cp Leopard.jar ac.LeopardMain  de.freehamburger.apk >>Leopard_app.txt   2>&1