java -cp Leopard.jar  ac.LeopardMain ./Apks/com.fr3ts0n.ecu.gui.androbd.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.machiav3lli.backup.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.dozingcatsoftware.bouncy.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.cweb.messenger.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/godau.fynn.usagedirect.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/mobi.omegacentauri.SendReduced.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.i2p.android.router.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.sudoq.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/fr.gouv.android.stopcovid.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/is.xyz.omw.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/it.niedermann.owncloud.notes.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/ch.hgdev.toposuite.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/top.donmor.tiddloid.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.tadris.fitness.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.pfiers.osmfocus.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/su.sadrobot.yashlang.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/ru.yanus171.feedexfork.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/dev.corruptedark.openchaoschess.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.corona.tracing.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.osmand.plus.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.farmerbb.taskbar.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.drhoffmannsoftware.calcvac.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.nhiroki.bluelineconsole.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.securefilemanager.app.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/app.fedilab.tubelab.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/org.snikket.android.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.eidottermihi.raspicheck.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.github.axet.audiorecorder.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.reimardoeffinger.quickdic.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.cg.lrceditor.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.sapuseven.untis.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.ichi2.anki.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.shatteredpixel.shatteredpixeldungeon.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/posidon.launcher.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.subhamtyagi.ocr.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.smartpack.smartflasher.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/im.status.ethereum.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/nodomain.freeyourgadget.gadgetbridge.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.mikifus.padland.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.silinote.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.nextcloud.client.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/la.daube.photochiotte.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.installalogs.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.iatfei.streakalarm.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.gimranov.zandy.app.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/me.blog.korn123.easydiary.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.simplemobiletools.gallery.pro.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.poupa.attestationdeplacement.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.ubergeek42.WeechatAndroid.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.sourceforge.opencamera.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/it.niedermann.nextcloud.deck.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.tunerly.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.storchp.opentracks.osmplugin.offline.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/me.tripsit.tripmobile.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/se.lublin.mumla.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.tnibler.cryptocam.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/espero.jiofibatterynotifier.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/security.pEp.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.storchp.opentracks.osmplugin.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.github.cvzi.darkmodewallpaper.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.mendhak.gpslogger.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/app.fedilab.lite.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.fff.ccgt.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.rwth_aachen.phyphox.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.limbo.emu.main.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.smartpack.packagemanager.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.limelight.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.ghostsq.commander.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.alienpants.leafpicrevived.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.wireguard.android.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/t20kdc.offlinepuzzlesolver.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.dar.nclientv2.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/theredspy15.ltecleanerfoss.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.smartpack.scriptmanager.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.monocles.chat.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.osfans.trime.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/eu.veldsoft.ithaka.board.game.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/namlit.siteswapgenerator.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.chronosx88.yggdrasil.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.syss.MifareClassicTool.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/app.fedilab.fedilabtube.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/fr.gouv.etalab.mastodon.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/eu.siacs.conversations.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.appmindlab.nano.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.oF2pks.classyshark3xodus.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/app.fedilab.mobilizon.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.nextcloud.android.beta.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.owncloud.android.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.machiav3lli.derdiedas.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.datastopwatch.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.igisw.openmoneybox.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/player.efis.cfd.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.gh4a.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.saveastxt.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.asdoi.gymwen.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.pixart.messenger.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/godau.fynn.usagedirect.system.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.github.axet.bookreader.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.nulide.findmydevice.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.jovial.jrpn.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/dev.msfjarvis.aps.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.kollnig.missioncontrol.fdroid.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.perflyst.twire.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.github.gschwind.fiddle_assistant.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/at.jclehner.rxdroid.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.smartpack.kernelprofiler.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/xyz.myachin.downloader.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.randomfilemaker.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.kylecorry.trail_sense.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.brentpanther.bitcoinwidget.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.luhmer.owncloudnewsreader.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.muntashirakon.AppManager.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.blau.android.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/menion.android.whereyougo.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.haringeymobile.ukweather.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.ominous.quickweather.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.dosse.bwentrain.androidPlayer.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/kiwi.root.an2linuxclient.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.zoffcc.applications.trifa.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/xyz.myachin.saveto.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.justdave.nwsweatheralertswidget.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.spisoft.quicknote.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/dnsfilter.android.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/eu.sum7.conversations.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/sushi.hardcore.droidfs.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/apps.amine.bou.readerforselfoss.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.rochefort.childmonitor.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.github.axet.torrentclient.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.sourceforge.x11basic.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.freerdp.afreerdp.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.dosse.dozeoff.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/io.github.folderlogs.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/vocabletrainer.heinecke.aron.vocabletrainer.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/ltd.evilcorp.atox.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.calcitem.sanmill.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.smartpack.kernelmanager.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.bible.android.activity.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/lu.fisch.canze.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/net.ktnx.mobileledger.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.apk ./android-platforms.editor.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.dosse.airpods.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/com.swordfish.lemuroid.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/im.quicksy.client.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.dennisguse.opentracks.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/site.leos.apps.lespas.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/player.efis.mfd.apk ./android-platforms
java -cp Leopard.jar  ac.LeopardMain ./Apks/de.freehamburger.apk ./android-platforms